### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by moh1122** [jaredalexander/ios-pushup-tracker#1]
Hello
thats a great project but its not building im getting lots of errors and i opened pushups.xcworkspace
can you help plz ?
Thank you

**Comment by jaredalexander** [comment]
Please ensure you have the latest version of Xcode and that you have run a pod install from the root directory before trying to build the project. Let me know if that helps.

**Comment by moh1122** [comment]
hello thanks for your quick reply well i have xcode 7.2 and i did run a pod install from the root directory, but its saying 'could not automatically select an Xcode project. Specify one in your Podfile like so: xcodeproj 'path/to/project.xcodeproj'
can you tell me how to specify that.

Thank you

**Comment by moh1122** [comment]
when i fixed that and i one have one error now which is no visible @interface for 'BFExexutor' declares the selector 'executorWithDispatchQueue'

Any clue?

**Comment by moh1122** [comment]
well i fixed that and pods are installed completely but i  have one error now which is no visible @interface for 'BFExexutor' declares the selector 'executorWithDispatchQueue' This error is in BFTask+Private.m

Any clue?

**Comment by profjared** [comment]
That file is part of the Parse CocoaPod - my only thought is that somehow Parse is not being fully pulled into your project. Make sure you are opening pushups.xcworkspace (as opposed to pushups.xcodeproj). Once you open the workspace in Xcode, ensure the Pods/Parse/BFTask+Private.m path exists in your Project Navigator. If it doesn't exist, maybe there was an issue with your pod install.

**Comment by moh1122** [comment]
thnks man ts working well now
great proj :+1:
