### ISSUE TITLE
Building parse server

### ISSUE THREAD

**Issue by moh1122** [jaredalexander/ios-pushup-tracker#2]
Hello
Im building a parse server on heroku so i can build the proj seperate from parse.com
Can you please tell me how to use the parse SDK with Parse server. The appID and client Key are already there in your project but I want to add my own server to appdelegate, do you know how can i do that.
Thank you
MM

**Comment by jaredalexander** [comment]
Check out https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide
